# ! MongoDB configs.

database: "cosmos"
requires_auth: Yes
username: null
password: null
host: 127.0.0.1
port: 27017
uri: "mongodb://thecosmos:I2vhyffcplsVoAbr@tc-discord-bot-shard-00-00-i4l5o.mongodb.net:27017,tc-discord-bot-shard-00-01-i4l5o.mongodb.net:27017,tc-discord-bot-shard-00-02-i4l5o.mongodb.net:27017/test?ssl=true&replicaSet=tc-discord-bot-shard-0&authSource=admin"


# ! DiscordDB configs.

channel_id: 586787372490948608
